- name: This playbook will install, configure web root folder and deploys a custom web page 
  hosts: all
  become: yes
  vars:
  - greeting_msg: Welcome to DevOps!
  - provisioner_tool: Terraform 
  - cfg_mgr_tool: Ansible

  tasks:
  - name: Install nginx web server
    apt: name=nginx state=latest update_cache=yes 

  - name: Create the custom web root folder
    file: path=/var/html mode=0777 state=directory owner="{{ansible_user}}" group="{{ansible_user}}"

  - name: Deploy custom web page into custom web root folder
    template: src=index.html.j2 dest=/var/html/index.html

  - name: Configure nginx web server to use custom web root folder
    copy: src=default  dest=/etc/nginx/sites-available/default
  
  - name: Restart nginx web server service
    service: name=nginx state=restarted enabled=true

